title: Power system load flow analysis toolkit
description: trying to write Load flow analysis programs in python

# theme: jekyll-theme-slate
remote-theme: abhn/Soot-Spirits


plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
 - jekyll-include-cache




markdown: kramdown
mathjax:
  enabled: true


exclude:
 - Gemfile
 - Gemfile.lock