title: Power system load flow analysis toolkit
description: trying to write Load flow analysis programs in python

# theme: jekyll-theme-slate
remote_theme: mmistakes/minimal-mistakes



plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
 - jekyll-include-cache


logo: /assets/me.jpg # an absolute or relative image path to use as the site logo
mdl_colors: indigo-pink # a supported Material Design Lite color scheme
copyright: Sree Sai Nandini Gundraju # will override the copyright notice (default is site title)
search: true # enabled by default, set to false to disable site search
menu_style: dropdown # will only show child menu items for the main item selected

markdown: kramdown
mathjax:
  enabled: true

mermaid:
  version: "11.14.1"


