title: Power system load flow analysis toolkit
description: trying to write Load flow analysis programs in python

remote-theme: pages-themes/slate


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-include-cache




markdown: kramdown
mathjax:
  enabled: true


exclude:
 - Gemfile
 - Gemfile.lock